Use FluentAssertions instead of xUnit assertions
FluentAssertions is much more expressive than xUnit assertions. It also gives much better error messages when the assertions fail. For example:

```
FluentAssertions.Execution.AssertionFailedException: Expected v.Kind to be Utc, but found Unspecified.
```

The assertions have been reviewed manually to match the most expressive fluent assertion equivalents. For example `Assert.True(result > 0)` has been translated to `result.Should().BeGreaterThan(0)` instead of `(result > 0).Should().BeTrue()` in order to get the best possible assertion failure messages.

Finally, by using FluentAssertions, we can get rid of the Xunit.Assert static class in fake_xunit. The number of asserts for a given test has been lost, but let's hope a solution to this might exist, see [How to count the number of assertions inside an AssertionScope?][1].

[1]: https://github.com/fluentassertions/fluentassertions/issues/1380